# Generated by Django 6.0.4 on 2026-04-12 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminHome', '0001_initial'),
        ('applicant', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=200, null=True)),
                ('plot_status', models.BooleanField()),
                ('scheme', models.CharField(max_length=20)),
                ('strt_dt', models.DateField()),
                ('end_dt', models.DateField()),
                ('house_no', models.IntegerField()),
                ('amount_tt', models.IntegerField()),
                ('normal_fnd', models.IntegerField()),
                ('other_fnd', models.IntegerField()),
                ('criteria', models.TextField(max_length=100)),
                ('sq_feet', models.IntegerField()),
                ('no_rooms', models.IntegerField()),
                ('hm_details', models.CharField(max_length=200)),
                ('image1', models.FileField(upload_to='images')),
                ('image2', models.FileField(upload_to='images')),
                ('sub_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='complrep_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=2000)),
                ('status', models.CharField(default='successfully replied', max_length=20)),
                ('complaint', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applicant.complaint_model')),
            ],
            options={
                'db_table': 'complaintreply',
            },
        ),
        migrations.CreateModel(
            name='plot_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(max_length=20)),
                ('tt_acres', models.IntegerField()),
                ('hm_acres', models.IntegerField()),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHome.district_model')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.village_model')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='officer.project_model')),
            ],
            options={
                'db_table': 'plot',
            },
        ),
        migrations.CreateModel(
            name='quotenot_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_code', models.IntegerField(null=True)),
                ('quote_name', models.CharField(max_length=200)),
                ('open_date', models.DateField(default=django.utils.timezone.now)),
                ('close_date', models.DateField(default=django.utils.timezone.now)),
                ('quote_doc1', models.FileField(upload_to='images')),
                ('quote_doc2', models.FileField(upload_to='images')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(default='New', max_length=20)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.project_model')),
                ('QuotationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.quote_model')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='surveyreport_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittedby', models.CharField(max_length=200)),
                ('sub_date', models.DateField(default=django.utils.timezone.now)),
                ('verifyby', models.CharField(max_length=200)),
                ('verify_date', models.DateField(default=django.utils.timezone.now)),
                ('verifystatus', models.CharField(default='New', max_length=20)),
                ('reject_reason', models.CharField(max_length=200)),
                ('appln_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.applicant_model')),
            ],
            options={
                'db_table': 'surveyreport',
            },
        ),
    ]
