# Generated by Django 6.0.4 on 2026-04-12 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='designation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='district_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='faqQuest_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqQuest', models.CharField(max_length=200)),
                ('faqAns', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'faqQuest',
            },
        ),
        migrations.CreateModel(
            name='quote_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotetype', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'quotetype',
            },
        ),
        migrations.CreateModel(
            name='Role_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=30)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='village_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=20)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHome.district_model')),
            ],
            options={
                'db_table': 'village',
            },
        ),
        migrations.CreateModel(
            name='office_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=10)),
                ('regdate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('desig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.designation_model')),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.district_model')),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.village_model')),
            ],
            options={
                'db_table': 'office',
            },
        ),
    ]
