# Generated by Django 6.0.4 on 2026-04-12 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminHome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='INACTIVE', max_length=20)),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='builder_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(max_length=20)),
                ('licenseno', models.IntegerField()),
                ('licencedate', models.DateField()),
                ('id_proof', models.FileField(upload_to='images')),
                ('up_doc', models.FileField(upload_to='images')),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='INACTIVE', max_length=20)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.district_model')),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'builder',
            },
        ),
    ]
