# Generated by Django 6.0.4 on 2026-04-12 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officer', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reqapply_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amt', models.IntegerField()),
                ('doc1', models.FileField(upload_to='images')),
                ('doc2', models.FileField(upload_to='images')),
                ('subdate', models.DateField(default=django.utils.timezone.now)),
                ('bid_status', models.CharField(default='New', max_length=20)),
                ('work_status', models.CharField(default='New', max_length=20)),
                ('builderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.builder_model')),
                ('quote_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.quotenot_model')),
            ],
            options={
                'db_table': 'reqapply',
            },
        ),
    ]
