# Generated by Django 6.0.4 on 2026-04-12 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('adminHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(null=True)),
                ('complaints', models.TextField(max_length=2000)),
                ('send_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='INACTIVE', max_length=20)),
                ('appln_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.applicant_model')),
            ],
        ),
        migrations.CreateModel(
            name='request_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appln_no', models.IntegerField(null=True)),
                ('adhar_no', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('photo', models.FileField(upload_to='images')),
                ('app_job', models.CharField(max_length=200)),
                ('idproof', models.FileField(upload_to='images')),
                ('plot_available', models.CharField(max_length=200)),
                ('cent', models.IntegerField()),
                ('survey_no', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('loc_type', models.CharField(max_length=200)),
                ('rationcard_no', models.IntegerField()),
                ('status', models.CharField(default='New', max_length=20)),
                ('member_no', models.IntegerField(null=True)),
                ('Gov_emp_no', models.IntegerField(null=True)),
                ('Anual_income', models.IntegerField(null=True)),
                ('Income_certf', models.CharField(max_length=200, null=True)),
                ('applydate', models.DateField(default=django.utils.timezone.now)),
                ('Verify_status', models.CharField(max_length=200, null=True)),
                ('Work_status', models.CharField(max_length=200, null=True)),
                ('applicantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.applicant_model')),
                ('plot_distid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHome.district_model')),
                ('plot_villageid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminHome.village_model')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
